Jmol.___JmolDate="$Date: 2026-02-12 11:47:45 -0600 (Thu, 12 Feb 2026) $"
Jmol.___fullJmolProperties="src/org/jmol/viewer/Jmol.properties"
Jmol.___JmolVersion="16.3.49" // (legacy) also 16.3.50 (swingJS) 
